name: Notify Telegram on PR & Commits

on:
  pull_request:
    types: [opened, closed]
  push:
    branches:
      - main
      - dev

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Notification
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ] && [ "${{ github.event.action }}" == "opened" ]; then
            MESSAGE="New Pull Request in ${{ github.repository }}%0AAuthor: [${{ github.actor }}](https://github.com/${{ github.actor }})%0ALink: ${{ github.event.pull_request.html_url }}%0ATitle: ${{ github.event.pull_request.title }}"
          
          elif [ "${{ github.event_name }}" == "pull_request" ] && [ "${{ github.event.action }}" == "closed" ] && [ "${{ github.event.pull_request.merged }}" == "true" ]; then
            MESSAGE="Pull Request merged in ${{ github.repository }}%0AAuthor: [${{ github.actor }}](https://github.com/${{ github.actor }})%0ALink: ${{ github.event.pull_request.html_url }}%0ATitle: ${{ github.event.pull_request.title }}"
          
          elif [ "${{ github.event_name }}" == "push" ]; then
            MESSAGE="New commit pushed to ${{ github.ref_name }} in ${{ github.repository }}%0AAuthor: [${{ github.actor }}](https://github.com/${{ github.actor }})%0ACommit message: ${{ github.event.head_commit.message }}%0ALink: https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
          
          else
            exit 0
          fi

          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d text="$MESSAGE" \
            -d parse_mode=Markdown
